Solution
mate-academy/js_center_spider_DOM pull request #264
Opened 2021-10-01 18:36 UTC by Daerniss

2021-10-03 15:55 UTC, Bohdan-Kochetov approved these changes

2021-10-04 11:56 UTC, OleksiiBlezniuk requested changes

2021-10-04 11:56 UTC, OleksiiBlezniuk commented on cypress/integration/centerSpider.spec.js
>        });
Что это за файл у тебя в коммите?🤔

2021-10-04 12:04 UTC, Daerniss commented on cypress/integration/centerSpider.spec.js
>        });
Я без понятия, гит начал ругаться на коммит.

2021-10-05 07:03 UTC, closed without merging