tests added
mate-academy/js_center_spider_DOM pull request #96
Opened 2020-11-09 10:44 UTC by iBrianWarner

2020-11-19 07:13 UTC, YuriiHoliuk requested changes

2020-11-19 07:13 UTC, YuriiHoliuk commented on cypress.json
> +}
видаляйте зайві файли

2020-11-19 07:13 UTC, YuriiHoliuk commented on cypress/integration/js_center_spider.spec.js
> +describe(('Tests'), () => {
Not "Tests", You should write here about what you describe in this block. Ex:
`Spider app` OR `Spider`, OR `Spider image` etc

Unneeded parenthesis
```suggestion
describe('Tests', () => {
```

2020-11-19 07:13 UTC, YuriiHoliuk commented on cypress/integration/js_center_spider.spec.js
> +    cy.get("body").then(($body) => {
Use only single quotes for strings

2020-11-19 07:13 UTC, YuriiHoliuk commented on cypress/integration/js_center_spider.spec.js
> +      };
Bad test, there are too many ways how to center block, avoid so complex style selectors

2020-11-19 07:13 UTC, YuriiHoliuk commented on cypress/support/commands.js
> +});
Є ще щось що використовуєте завжди, треба таке вссюди додати, якщо буде потрібно

2020-11-19 15:38 UTC, iBrianWarner commented on cypress.json
> +}
видалив baseUrl, сам файл залишив

2020-11-19 15:39 UTC, iBrianWarner commented on cypress/integration/js_center_spider.spec.js
> +describe(('Tests'), () => {
перейменував describe та it, видалив use strict

2020-11-19 15:39 UTC, iBrianWarner commented on cypress/integration/js_center_spider.spec.js
> +    cy.get("body").then(($body) => {
виправив

2020-11-19 15:39 UTC, iBrianWarner commented on cypress/integration/js_center_spider.spec.js
> +      };
повністю переписав тест

2020-11-19 15:40 UTC, iBrianWarner commented on cypress/support/commands.js
> +});
видалив команду, так як не знадобилася. також повидаляв зайві файли та папки.

2020-11-19 17:45 UTC, YuriiHoliuk approved these changes

2020-11-19 17:45 UTC, YuriiHoliuk commented on cypress/integration/centerSpider.spec.js
> +        const spiderLeft = $spider.get(0).getBoundingClientRect().left;
$wall.get(0), $spider.get(0) - все що повторюється варто виносити в змінні

2020-11-20 12:51 UTC, roman-mate commented on .github/workflows/test.yml
> +      if: ${{ always() }}
is this needed?

2020-11-20 12:51 UTC, roman-mate commented on .github/workflows/test.yml
> +        path: backstop_data
are we using backstop here?

2020-11-20 12:51 UTC, roman-mate commented on cypress/integration/centerSpider.spec.js
> +/* eslint-disable strict */
why?

2020-11-20 12:51 UTC, roman-mate commented on cypress/integration/centerSpider.spec.js
> +    cy.wait(1000);
why is this needed?

2020-11-20 12:51 UTC, roman-mate commented on cypress/support/commands.js
> +// ***********************************************
is this file needed?

2020-11-20 13:51 UTC, closed without merging